In [1]:
import pandas as pd
import requests

In [2]:
url = "https://dummyjson.com/users"
data = requests.get(url)
data.status_code

200

In [ ]:
user_data = data.json()
user_data

In [23]:
nom_data = pd.json_normalize(user_data["users"])
nom_data

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,company.address.city,company.address.state,company.address.stateCode,company.address.postalCode,company.address.coordinates.lat,company.address.coordinates.lng,company.address.country,crypto.coin,crypto.wallet,crypto.network
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,San Francisco,Wisconsin,WI,37657,71.814525,-161.150263,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,Los Angeles,New Hampshire,NH,73442,79.098326,-119.624845,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,Dallas,Nevada,NV,88511,20.086743,-34.577107,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,Fort Worth,Pennsylvania,PA,27768,54.911930,-79.498328,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,San Antonio,Idaho,ID,21965,44.346545,-26.944701,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
5,6,Olivia,Wilson,,23,female,olivia.wilson@x.dummyjson.com,+91 607-295-6448,oliviaw,oliviawpass,...,Indianapolis,Oklahoma,OK,74263,74.986644,-132.916888,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
6,7,Alexander,Jones,,39,male,alexander.jones@x.dummyjson.com,+61 260-824-4986,alexanderj,alexanderjpass,...,Washington,Kansas,KS,27858,-75.462366,-128.025697,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
7,8,Ava,Taylor,,28,female,ava.taylor@x.dummyjson.com,+1 458-853-7877,avat,avatpass,...,Austin,Colorado,CO,47592,87.970083,-42.769351,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
8,9,Ethan,Martinez,,34,male,ethan.martinez@x.dummyjson.com,+92 933-608-5081,ethanm,ethanmpass,...,Chicago,Florida,FL,28100,-67.452080,-23.209886,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
9,10,Isabella,Anderson,Davis,32,female,isabella.anderson@x.dummyjson.com,+49 770-658-4885,isabellad,isabelladpass,...,San Diego,Maryland,MD,63847,-25.843393,-62.692681,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
10,11,Liam,Garcia,,30,male,liam.garcia@x.dummyjson.com,+92 870-217-6201,liamg,liamgpass,...,Philadelphia,Connecticut,CT,79574,-81.841588,31.794230,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
11,12,Mia,Rodriguez,,25,female,mia.rodriguez@x.dummyjson.com,+49 989-461-8403,miar,miarpass,...,Philadelphia,New Jersey,NJ,57518,85.455933,164.246103,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
12,13,Noah,Hernandez,,41,male,noah.hernandez@x.dummyjson.com,+49 393-605-6968,noahh,noahhpass,...,Seattle,Oregon,OR,83474,19.490447,-13.173207,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
13,14,Charlotte,Lopez,Martinez,37,female,charlotte.lopez@x.dummyjson.com,+44 373-953-5028,charlottem,charlottempass,...,Los Angeles,Montana,MT,17779,-18.371256,22.566258,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
14,15,William,Gonzalez,,33,male,william.gonzalez@x.dummyjson.com,+81 905-252-7319,williamg,williamgpass,...,San Jose,Missouri,MO,29673,24.169361,-29.395167,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
15,16,Avery,Perez,,26,female,avery.perez@x.dummyjson.com,+61 731-431-3457,averyp,averyppass,...,New York,Rhode Island,RI,45238,-53.318189,105.835271,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
16,17,Evelyn,Sanchez,,38,female,evelyn.sanchez@x.dummyjson.com,+1 623-880-6871,evelyns,evelynspass,...,San Diego,Minnesota,MN,89416,29.034592,-78.004598,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
17,18,Logan,Torres,,32,male,logan.torres@x.dummyjson.com,+81 507-434-8733,logant,logantpass,...,Denver,Minnesota,MN,71896,-24.654063,-147.255268,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
18,19,Abigail,Rivera,,29,female,abigail.rivera@x.dummyjson.com,+91 228-363-7806,abigailr,abigailrpass,...,Austin,Wisconsin,WI,51456,25.672938,-76.549670,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
19,20,Jackson,Evans,,35,male,jackson.evans@x.dummyjson.com,+44 468-628-6686,jacksone,jacksonepass,...,Chicago,Hawaii,HI,34725,-80.416937,-83.224516,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
20,21,Madison,Collins,,27,female,madison.collins@x.dummyjson.com,+81 259-957-5711,madisonc,madisoncpass,...,San Diego,Delaware,DE,63144,1.629613,23.232982,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
21,22,Elijah,Stewart,,34,male,elijah.stewart@x.dummyjson.com,+44 468-357-7872,elijahs,elijahspass,...,Washington,South Dakota,SD,19039,61.279254,-12.607767,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
22,23,Chloe,Morales,,40,female,chloe.morales@x.dummyjson.com,+92 468-541-7133,chloem,chloempass,...,Houston,North Carolina,NC,10385,40.098115,-1.762972,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
23,24,Mateo,Nguyen,,31,male,mateo.nguyen@x.dummyjson.com,+1 341-597-6694,mateon,mateonpass,...,Dallas,Louisiana,LA,78527,75.982676,164.459743,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
24,25,Harper,Kelly,Evans,28,female,harper.kelly@x.dummyjson.com,+92 518-863-2863,harpere,harperepass,...,Austin,North Carolina,NC,68274,-15.423746,149.298887,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
25,26,Evelyn,Gonzalez,,36,female,evelyn.gonzalez@x.dummyjson.com,+61 708-508-4638,evelyng,evelyngpass,...,Jacksonville,Wisconsin,WI,45633,26.014021,40.572436,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
26,27,Daniel,Cook,,42,male,daniel.cook@x.dummyjson.com,+44 254-761-6843,danielc,danielcpass,...,San Francisco,South Dakota,SD,45305,21.323588,-83.531427,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
27,28,Lily,Lee,Brown,30,female,lily.lee@x.dummyjson.com,+1 808-757-9867,lilyb,lilybpass,...,Phoenix,Wyoming,WY,85797,72.231441,-158.147245,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
28,29,Henry,Hill,,39,male,henry.hill@x.dummyjson.com,+1 240-833-4680,henryh,henryhpass,...,San Francisco,West Virginia,WV,61805,-59.936335,-12.405368,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
29,30,Addison,Wright,,33,female,addison.wright@x.dummyjson.com,+1 514-384-3300,addisonw,addisonwpass,...,San Diego,Michigan,MI,85777,65.324413,87.142893,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)

In [27]:
nom_data.columns = nom_data.columns.str.replace("company.address.", "", regex=False)

In [30]:
nom_data.columns

Index(['id', 'firstName', 'lastName', 'maidenName', 'age', 'gender', 'email',
       'phone', 'username', 'password', 'birthDate', 'image', 'bloodGroup',
       'height', 'weight', 'eyeColor', 'ip', 'macAddress', 'university', 'ein',
       'ssn', 'userAgent', 'role', 'hair.color', 'hair.type',
       'address.address', 'address.city', 'address.state', 'address.stateCode',
       'address.postalCode', 'address.coordinates.lat',
       'address.coordinates.lng', 'address.country', 'bank.cardExpire',
       'bank.cardNumber', 'bank.cardType', 'bank.currency', 'bank.iban',
       'company.department', 'company.name', 'company.title', 'address',
       'city', 'state', 'stateCode', 'postalCode', 'coordinates.lat',
       'coordinates.lng', 'country', 'crypto.coin', 'crypto.wallet',
       'crypto.network'],
      dtype='str')

In [ ]:
nom_data

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,city,state,stateCode,postalCode,coordinates.lat,coordinates.lng,country,crypto.coin,crypto.wallet,crypto.network
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,San Francisco,Wisconsin,WI,37657,71.814525,-161.150263,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,Los Angeles,New Hampshire,NH,73442,79.098326,-119.624845,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,Dallas,Nevada,NV,88511,20.086743,-34.577107,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,Fort Worth,Pennsylvania,PA,27768,54.911930,-79.498328,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,San Antonio,Idaho,ID,21965,44.346545,-26.944701,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
5,6,Olivia,Wilson,,23,female,olivia.wilson@x.dummyjson.com,+91 607-295-6448,oliviaw,oliviawpass,...,Indianapolis,Oklahoma,OK,74263,74.986644,-132.916888,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
6,7,Alexander,Jones,,39,male,alexander.jones@x.dummyjson.com,+61 260-824-4986,alexanderj,alexanderjpass,...,Washington,Kansas,KS,27858,-75.462366,-128.025697,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
7,8,Ava,Taylor,,28,female,ava.taylor@x.dummyjson.com,+1 458-853-7877,avat,avatpass,...,Austin,Colorado,CO,47592,87.970083,-42.769351,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
8,9,Ethan,Martinez,,34,male,ethan.martinez@x.dummyjson.com,+92 933-608-5081,ethanm,ethanmpass,...,Chicago,Florida,FL,28100,-67.452080,-23.209886,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
9,10,Isabella,Anderson,Davis,32,female,isabella.anderson@x.dummyjson.com,+49 770-658-4885,isabellad,isabelladpass,...,San Diego,Maryland,MD,63847,-25.843393,-62.692681,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
10,11,Liam,Garcia,,30,male,liam.garcia@x.dummyjson.com,+92 870-217-6201,liamg,liamgpass,...,Philadelphia,Connecticut,CT,79574,-81.841588,31.794230,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
11,12,Mia,Rodriguez,,25,female,mia.rodriguez@x.dummyjson.com,+49 989-461-8403,miar,miarpass,...,Philadelphia,New Jersey,NJ,57518,85.455933,164.246103,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
12,13,Noah,Hernandez,,41,male,noah.hernandez@x.dummyjson.com,+49 393-605-6968,noahh,noahhpass,...,Seattle,Oregon,OR,83474,19.490447,-13.173207,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
13,14,Charlotte,Lopez,Martinez,37,female,charlotte.lopez@x.dummyjson.com,+44 373-953-5028,charlottem,charlottempass,...,Los Angeles,Montana,MT,17779,-18.371256,22.566258,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
14,15,William,Gonzalez,,33,male,william.gonzalez@x.dummyjson.com,+81 905-252-7319,williamg,williamgpass,...,San Jose,Missouri,MO,29673,24.169361,-29.395167,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
15,16,Avery,Perez,,26,female,avery.perez@x.dummyjson.com,+61 731-431-3457,averyp,averyppass,...,New York,Rhode Island,RI,45238,-53.318189,105.835271,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
16,17,Evelyn,Sanchez,,38,female,evelyn.sanchez@x.dummyjson.com,+1 623-880-6871,evelyns,evelynspass,...,San Diego,Minnesota,MN,89416,29.034592,-78.004598,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
17,18,Logan,Torres,,32,male,logan.torres@x.dummyjson.com,+81 507-434-8733,logant,logantpass,...,Denver,Minnesota,MN,71896,-24.654063,-147.255268,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
18,19,Abigail,Rivera,,29,female,abigail.rivera@x.dummyjson.com,+91 228-363-7806,abigailr,abigailrpass,...,Austin,Wisconsin,WI,51456,25.672938,-76.549670,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
19,20,Jackson,Evans,,35,male,jackson.evans@x.dummyjson.com,+44 468-628-6686,jacksone,jacksonepass,...,Chicago,Hawaii,HI,34725,-80.416937,-83.224516,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
20,21,Madison,Collins,,27,female,madison.collins@x.dummyjson.com,+81 259-957-5711,madisonc,madisoncpass,...,San Diego,Delaware,DE,63144,1.629613,23.232982,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
21,22,Elijah,Stewart,,34,male,elijah.stewart@x.dummyjson.com,+44 468-357-7872,elijahs,elijahspass,...,Washington,South Dakota,SD,19039,61.279254,-12.607767,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
22,23,Chloe,Morales,,40,female,chloe.morales@x.dummyjson.com,+92 468-541-7133,chloem,chloempass,...,Houston,North Carolina,NC,10385,40.098115,-1.762972,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
23,24,Mateo,Nguyen,,31,male,mateo.nguyen@x.dummyjson.com,+1 341-597-6694,mateon,mateonpass,...,Dallas,Louisiana,LA,78527,75.982676,164.459743,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
24,25,Harper,Kelly,Evans,28,female,harper.kelly@x.dummyjson.com,+92 518-863-2863,harpere,harperepass,...,Austin,North Carolina,NC,68274,-15.423746,149.298887,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
25,26,Evelyn,Gonzalez,,36,female,evelyn.gonzalez@x.dummyjson.com,+61 708-508-4638,evelyng,evelyngpass,...,Jacksonville,Wisconsin,WI,45633,26.014021,40.572436,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
26,27,Daniel,Cook,,42,male,daniel.cook@x.dummyjson.com,+44 254-761-6843,danielc,danielcpass,...,San Francisco,South Dakota,SD,45305,21.323588,-83.531427,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
27,28,Lily,Lee,Brown,30,female,lily.lee@x.dummyjson.com,+1 808-757-9867,lilyb,lilybpass,...,Phoenix,Wyoming,WY,85797,72.231441,-158.147245,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
28,29,Henry,Hill,,39,male,henry.hill@x.dummyjson.com,+1 240-833-4680,henryh,henryhpass,...,San Francisco,West Virginia,WV,61805,-59.936335,-12.405368,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
29,30,Addison,Wright,,33,female,addison.wright@x.dummyjson.com,+1 514-384-3300,addisonw,addisonwpass,...,San Diego,Michigan,MI,85777,65.324413,87.142893,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)

In [21]:
ff = pd.DataFrame(nom_data)
ff

                                               users  total  skip  limit
0  [{'id': 1, 'firstName': 'Emily', 'lastName': '...    208     0     30

In [6]:
user_data["users"]

[{'id': 1,
  'firstName': 'Emily',
  'lastName': 'Johnson',
  'maidenName': 'Smith',
  'age': 29,
  'gender': 'female',
  'email': 'emily.johnson@x.dummyjson.com',
  'phone': '+81 965-431-3024',
  'username': 'emilys',
  'password': 'emilyspass',
  'birthDate': '1996-5-30',
  'image': 'https://dummyjson.com/icon/emilys/128',
  'bloodGroup': 'O-',
  'height': 193.24,
  'weight': 63.16,
  'eyeColor': 'Green',
  'hair': {'color': 'Brown', 'type': 'Curly'},
  'ip': '42.48.100.32',
  'address': {'address': '626 Main Street',
   'city': 'Phoenix',
   'state': 'Mississippi',
   'stateCode': 'MS',
   'postalCode': '29112',
   'coordinates': {'lat': -77.16213, 'lng': -92.084824},
   'country': 'United States'},
  'macAddress': '47:fa:41:18:ec:eb',
  'university': 'University of Wisconsin--Madison',
  'bank': {'cardExpire': '05/28',
   'cardNumber': '3693233511855044',
   'cardType': 'Diners Club International',
   'currency': 'GBP',
   'iban': 'GB74MH2UZLR9TRPHYNU8F8'},
  'company': {'department': 'Engineering',
   'name': 'Dooley, Kozey and Cronin',
   'title': 'Sales Manager',
   'address': {'address': '263 Tenth Street',
    'city': 'San Francisco',
    'state': 'Wisconsin',
    'stateCode': 'WI',
    'postalCode': '37657',
    'coordinates': {'lat': 71.814525, 'lng': -161.150263},
    'country': 'United States'}},
  'ein': '977-175',
  'ssn': '900-590-289',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 2,
  'firstName': 'Michael',
  'lastName': 'Williams',
  'maidenName': '',
  'age': 36,
  'gender': 'male',
  'email': 'michael.williams@x.dummyjson.com',
  'phone': '+49 258-627-6644',
  'username': 'michaelw',
  'password': 'michaelwpass',
  'birthDate': '1989-8-10',
  'image': 'https://dummyjson.com/icon/michaelw/128',
  'bloodGroup': 'B+',
  'height': 186.22,
  'weight': 76.32,
  'eyeColor': 'Red',
  'hair': {'color': 'Green', 'type': 'Straight'},
  'ip': '12.13.116.142',
  'address': {'address': '385 Fifth Street',
   'city': 'Houston',
   'state': 'Alabama',
   'stateCode': 'AL',
   'postalCode': '38807',
   'coordinates': {'lat': 22.815468, 'lng': 115.608581},
   'country': 'United States'},
  'macAddress': '79:15:78:99:60:aa',
  'university': 'Ohio State University',
  'bank': {'cardExpire': '01/30',
   'cardNumber': '3530633803003665',
   'cardType': 'JCB',
   'currency': 'USD',
   'iban': 'DE26362283149158045865'},
  'company': {'department': 'Support',
   'name': 'Spinka - Dickinson',
   'title': 'Support Specialist',
   'address': {'address': '395 Main Street',
    'city': 'Los Angeles',
    'state': 'New Hampshire',
    'stateCode': 'NH',
    'postalCode': '73442',
    'coordinates': {'lat': 79.098326, 'lng': -119.624845},
    'country': 'United States'}},
  'ein': '912-602',
  'ssn': '108-953-962',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 3,
  'firstName': 'Sophia',
  'lastName': 'Brown',
  'maidenName': '',
  'age': 43,
  'gender': 'female',
  'email': 'sophia.brown@x.dummyjson.com',
  'phone': '+81 210-652-2785',
  'username': 'sophiab',
  'password': 'sophiabpass',
  'birthDate': '1982-11-6',
  'image': 'https://dummyjson.com/icon/sophiab/128',
  'bloodGroup': 'O-',
  'height': 177.72,
  'weight': 52.6,
  'eyeColor': 'Hazel',
  'hair': {'color': 'White', 'type': 'Wavy'},
  'ip': '214.225.51.195',
  'address': {'address': '1642 Ninth Street',
   'city': 'Washington',
   'state': 'Alabama',
   'stateCode': 'AL',
   'postalCode': '32822',
   'coordinates': {'lat': 45.289366, 'lng': 46.832664},
   'country': 'United States'},
  'macAddress': '12:a3:d3:6f:5c:5b',
  'university': 'Pepperdine University',
  'bank': {'cardExpire': '10/27',
   'cardNumber': '6011212053392887',
   'cardType': 'Discover',
   'currency': 'EUR',
   'iban': 'DE12191213468288004835'},
  'company': {'department': 'Research and Development',
   'name': 'Schiller - Zieme',
   'title': 'Accountant',
   'address': {'address': '1896 Washington Street',
    'city': 'Dallas',
    'state': 'Nevada',
    'stateCode': 'NV',
    'postalCode': '88511',
    'coordinates': {'lat': 20.086743, 'lng': -34.577107},
    'country': 'United States'}},
  'ein': '963-113',
  'ssn': '638-461-822',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 4,
  'firstName': 'James',
  'lastName': 'Davis',
  'maidenName': '',
  'age': 46,
  'gender': 'male',
  'email': 'james.davis@x.dummyjson.com',
  'phone': '+49 614-958-9364',
  'username': 'jamesd',
  'password': 'jamesdpass',
  'birthDate': '1979-5-4',
  'image': 'https://dummyjson.com/icon/jamesd/128',
  'bloodGroup': 'AB+',
  'height': 193.31,
  'weight': 62.1,
  'eyeColor': 'Amber',
  'hair': {'color': 'Blonde', 'type': 'Straight'},
  'ip': '101.118.131.66',
  'address': {'address': '238 Jefferson Street',
   'city': 'Seattle',
   'state': 'Pennsylvania',
   'stateCode': 'PA',
   'postalCode': '68354',
   'coordinates': {'lat': 16.782513, 'lng': -139.34723},
   'country': 'United States'},
  'macAddress': '10:7d:df:1f:97:58',
  'university': 'University of Southern California',
  'bank': {'cardExpire': '07/30',
   'cardNumber': '5303440212268149',
   'cardType': 'Mastercard',
   'currency': 'CAD',
   'iban': 'DE01300746880579852937'},
  'company': {'department': 'Support',
   'name': 'Pagac and Sons',
   'title': 'Research Analyst',
   'address': {'address': '1622 Lincoln Street',
    'city': 'Fort Worth',
    'state': 'Pennsylvania',
    'stateCode': 'PA',
    'postalCode': '27768',
    'coordinates': {'lat': 54.91193, 'lng': -79.498328},
    'country': 'United States'}},
  'ein': '904-810',
  'ssn': '116-951-314',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 5,
  'firstName': 'Emma',
  'lastName': 'Miller',
  'maidenName': 'Johnson',
  'age': 31,
  'gender': 'female',
  'email': 'emma.miller@x.dummyjson.com',
  'phone': '+91 759-776-1614',
  'username': 'emmaj',
  'password': 'emmajpass',
  'birthDate': '1994-6-13',
  'image': 'https://dummyjson.com/icon/emmaj/128',
  'bloodGroup': 'AB-',
  'height': 192.8,
  'weight': 63.62,
  'eyeColor': 'Green',
  'hair': {'color': 'White', 'type': 'Straight'},
  'ip': '224.126.22.183',
  'address': {'address': '607 Fourth Street',
   'city': 'Jacksonville',
   'state': 'Colorado',
   'stateCode': 'CO',
   'postalCode': '26593',
   'coordinates': {'lat': 0.505589, 'lng': -157.43281},
   'country': 'United States'},
  'macAddress': '32:b9:7e:8d:f5:e8',
  'university': 'Northeastern University',
  'bank': {'cardExpire': '07/30',
   'cardNumber': '5237188057591130',
   'cardType': 'Mastercard',
   'currency': 'NZD',
   'iban': 'DE19182355652037133559'},
  'company': {'department': 'Human Resources',
   'name': 'Graham - Gulgowski',
   'title': 'Quality Assurance Engineer',
   'address': {'address': '1460 Sixth Street',
    'city': 'San Antonio',
    'state': 'Idaho',
    'stateCode': 'ID',
    'postalCode': '21965',
    'coordinates': {'lat': 44.346545, 'lng': -26.944701},
    'country': 'United States'}},
  'ein': '403-505',
  'ssn': '526-210-885',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 6,
  'firstName': 'Olivia',
  'lastName': 'Wilson',
  'maidenName': '',
  'age': 23,
  'gender': 'female',
  'email': 'olivia.wilson@x.dummyjson.com',
  'phone': '+91 607-295-6448',
  'username': 'oliviaw',
  'password': 'oliviawpass',
  'birthDate': '2002-4-20',
  'image': 'https://dummyjson.com/icon/oliviaw/128',
  'bloodGroup': 'B+',
  'height': 182.61,
  'weight': 58,
  'eyeColor': 'Hazel',
  'hair': {'color': 'Gray', 'type': 'Curly'},
  'ip': '249.178.112.207',
  'address': {'address': '547 First Street',
   'city': 'Fort Worth',
   'state': 'Tennessee',
   'stateCode': 'TN',
   'postalCode': '83843',
   'coordinates': {'lat': 75.32627, 'lng': -26.15285},
   'country': 'United States'},
  'macAddress': '9c:7f:ea:34:18:19',
  'university': 'University of North Carolina--Chapel Hill',
  'bank': {'cardExpire': '06/30',
   'cardNumber': '376320072452632',
   'cardType': 'American Express',
   'currency': 'NZD',
   'iban': 'DE21153814367894194071'},
  'company': {'department': 'Product Management',
   'name': 'Pfannerstill Inc',
   'title': 'Research Analyst',
   'address': {'address': '425 Sixth Street',
    'city': 'Indianapolis',
    'state': 'Oklahoma',
    'stateCode': 'OK',
    'postalCode': '74263',
    'coordinates': {'lat': 74.986644, 'lng': -132.916888},
    'country': 'United States'}},
  'ein': '921-709',
  'ssn': '836-772-168',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 7,
  'firstName': 'Alexander',
  'lastName': 'Jones',
  'maidenName': '',
  'age': 39,
  'gender': 'male',
  'email': 'alexander.jones@x.dummyjson.com',
  'phone': '+61 260-824-4986',
  'username': 'alexanderj',
  'password': 'alexanderjpass',
  'birthDate': '1986-10-20',
  'image': 'https://dummyjson.com/icon/alexanderj/128',
  'bloodGroup': 'AB-',
  'height': 153.89,
  'weight': 77.42,
  'eyeColor': 'Blue',
  'hair': {'color': 'White', 'type': 'Straight'},
  'ip': '166.204.84.32',
  'address': {'address': '664 Maple Street',
   'city': 'Indianapolis',
   'state': 'Delaware',
   'stateCode': 'DE',
   'postalCode': '86684',
   'coordinates': {'lat': 35.289664, 'lng': 7.063255},
   'country': 'United States'},
  'macAddress': 'd2:64:58:2d:1c:46',
  'university': 'University of Illinois--Urbana-Champaign',
  'bank': {'cardExpire': '12/29',
   'cardNumber': '5189302549548693',
   'cardType': 'Mastercard',
   'currency': 'PKR',
   'iban': 'DE67517655968963441488'},
  'company': {'department': 'Engineering',
   'name': 'Dickens - Beahan',
   'title': 'Web Developer',
   'address': {'address': '996 Eighth Street',
    'city': 'Washington',
    'state': 'Kansas',
    'stateCode': 'KS',
    'postalCode': '27858',
    'coordinates': {'lat': -75.462366, 'lng': -128.025697},
    'country': 'United States'}},
  'ein': '638-127',
  'ssn': '722-993-925',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 8,
  'firstName': 'Ava',
  'lastName': 'Taylor',
  'maidenName': '',
  'age': 28,
  'gender': 'female',
  'email': 'ava.taylor@x.dummyjson.com',
  'phone': '+1 458-853-7877',
  'username': 'avat',
  'password': 'avatpass',
  'birthDate': '1997-8-25',
  'image': 'https://dummyjson.com/icon/avat/128',
  'bloodGroup': 'AB-',
  'height': 168.47,
  'weight': 57.08,
  'eyeColor': 'Hazel',
  'hair': {'color': 'Red', 'type': 'Kinky'},
  'ip': '150.73.197.233',
  'address': {'address': '1197 First Street',
   'city': 'Fort Worth',
   'state': 'Rhode Island',
   'stateCode': 'RI',
   'postalCode': '24771',
   'coordinates': {'lat': -81.194833, 'lng': -87.948158},
   'country': 'United States'},
  'macAddress': '8d:2e:c2:d6:e7:a8',
  'university': 'University of Wisconsin--Madison',
  'bank': {'cardExpire': '08/30',
   'cardNumber': '5349974103330333',
   'cardType': 'Mastercard',
   'currency': 'EUR',
   'iban': 'FR94ZM2MMGL1EVYQE1ZLCVCFH83'},
  'company': {'department': 'Marketing',
   'name': 'Nikolaus Inc',
   'title': 'Chief Executive Officer',
   'address': {'address': '930 Lincoln Street',
    'city': 'Austin',
    'state': 'Colorado',
    'stateCode': 'CO',
    'postalCode': '47592',
    'coordinates': {'lat': 87.970083, 'lng': -42.769351},
    'country': 'United States'}},
  'ein': '297-762',
  'ssn': '257-419-109',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 9,
  'firstName': 'Ethan',
  'lastName': 'Martinez',
  'maidenName': '',
  'age': 34,
  'gender': 'male',
  'email': 'ethan.martinez@x.dummyjson.com',
  'phone': '+92 933-608-5081',
  'username': 'ethanm',
  'password': 'ethanmpass',
  'birthDate': '1991-2-12',
  'image': 'https://dummyjson.com/icon/ethanm/128',
  'bloodGroup': 'AB+',
  'height': 159.19,
  'weight': 68.81,
  'eyeColor': 'Hazel',
  'hair': {'color': 'Purple', 'type': 'Curly'},
  'ip': '63.191.127.71',
  'address': {'address': '466 Pine Street',
   'city': 'San Antonio',
   'state': 'Louisiana',
   'stateCode': 'LA',
   'postalCode': '72360',
   'coordinates': {'lat': 74.074918, 'lng': -25.312703},
   'country': 'United States'},
  'macAddress': '59:e:9e:e3:29:da',
  'university': 'Syracuse University',
  'bank': {'cardExpire': '10/27',
   'cardNumber': '3598603288061479',
   'cardType': 'JCB',
   'currency': 'GBP',
   'iban': 'GB26PND7D83JTW4HL6LZ71'},
  'company': {'department': 'Support',
   'name': 'Gorczany - Gottlieb',
   'title': 'Legal Counsel',
   'address': {'address': '1597 Oak Street',
    'city': 'Chicago',
    'state': 'Florida',
    'stateCode': 'FL',
    'postalCode': '28100',
    'coordinates': {'lat': -67.45208, 'lng': -23.209886},
    'country': 'United States'}},
  'ein': '790-434',
  'ssn': '569-650-348',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 10,
  'firstName': 'Isabella',
  'lastName': 'Anderson',
  'maidenName': 'Davis',
  'age': 32,
  'gender': 'female',
  'email': 'isabella.anderson@x.dummyjson.com',
  'phone': '+49 770-658-4885',
  'username': 'isabellad',
  'password': 'isabelladpass',
  'birthDate': '1993-6-10',
  'image': 'https://dummyjson.com/icon/isabellad/128',
  'bloodGroup': 'A-',
  'height': 150.56,
  'weight': 50.1,
  'eyeColor': 'Brown',
  'hair': {'color': 'Blonde', 'type': 'Curly'},
  'ip': '114.9.114.205',
  'address': {'address': '1964 Oak Street',
   'city': 'New York',
   'state': 'Utah',
   'stateCode': 'UT',
   'postalCode': '89352',
   'coordinates': {'lat': 41.331324, 'lng': 151.782727},
   'country': 'United States'},
  'macAddress': 'b1:b0:d0:a2:82:80',
  'university': 'California Institute of Technology (Caltech)',
  'bank': {'cardExpire': '03/30',
   'cardNumber': '3602093733952858',
   'cardType': 'Diners Club International',
   'currency': 'USD',
   'iban': 'DE12934874962442340025'},
  'company': {'department': 'Marketing',
   'name': 'Pollich - Hilpert',
   'title': 'Chief Financial Officer',
   'address': {'address': '1029 Adams Street',
    'city': 'San Diego',
    'state': 'Maryland',
    'stateCode': 'MD',
    'postalCode': '63847',
    'coordinates': {'lat': -25.843393, 'lng': -62.692681},
    'country': 'United States'}},
  'ein': '127-297',
  'ssn': '902-438-728',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 11,
  'firstName': 'Liam',
  'lastName': 'Garcia',
  'maidenName': '',
  'age': 30,
  'gender': 'male',
  'email': 'liam.garcia@x.dummyjson.com',
  'phone': '+92 870-217-6201',
  'username': 'liamg',
  'password': 'liamgpass',
  'birthDate': '1995-6-6',
  'image': 'https://dummyjson.com/icon/liamg/128',
  'bloodGroup': 'AB-',
  'height': 162.32,
  'weight': 93.16,
  'eyeColor': 'Violet',
  'hair': {'color': 'Red', 'type': 'Wavy'},
  'ip': '56.201.85.9',
  'address': {'address': '576 Fifth Street',
   'city': 'Denver',
   'state': 'South Dakota',
   'stateCode': 'SD',
   'postalCode': '57252',
   'coordinates': {'lat': -66.218177, 'lng': -145.340165},
   'country': 'United States'},
  'macAddress': '31:9a:28:8b:99:6c',
  'university': 'Ohio State University',
  'bank': {'cardExpire': '12/29',
   'cardNumber': '3614993744940956',
   'cardType': 'Diners Club International',
   'currency': 'USD',
   'iban': 'DE65581882748067758114'},
  'company': {'department': 'Services',
   'name': 'Considine - Torp',
   'title': 'Web Developer',
   'address': {'address': '27 Cedar Street',
    'city': 'Philadelphia',
    'state': 'Connecticut',
    'stateCode': 'CT',
    'postalCode': '79574',
    'coordinates': {'lat': -81.841588, 'lng': 31.79423},
    'country': 'United States'}},
  'ein': '326-604',
  'ssn': '933-784-949',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 12,
  'firstName': 'Mia',
  'lastName': 'Rodriguez',
  'maidenName': '',
  'age': 25,
  'gender': 'female',
  'email': 'mia.rodriguez@x.dummyjson.com',
  'phone': '+49 989-461-8403',
  'username': 'miar',
  'password': 'miarpass',
  'birthDate': '2000-8-4',
  'image': 'https://dummyjson.com/icon/miar/128',
  'bloodGroup': 'O-',
  'height': 188.08,
  'weight': 56.03,
  'eyeColor': 'Blue',
  'hair': {'color': 'Purple', 'type': 'Wavy'},
  'ip': '11.72.253.90',
  'address': {'address': '1627 Sixth Street',
   'city': 'Jacksonville',
   'state': 'West Virginia',
   'stateCode': 'WV',
   'postalCode': '41810',
   'coordinates': {'lat': 24.857497, 'lng': -34.865429},
   'country': 'United States'},
  'macAddress': '53:d7:a4:6:1e:58',
  'university': 'William & Mary',
  'bank': {'cardExpire': '02/29',
   'cardNumber': '343932350909214',
   'cardType': 'American Express',
   'currency': 'CAD',
   'iban': 'DE77118774979880310165'},
  'company': {'department': 'Accounting',
   'name': 'Miller, Schowalter and Wisozk',
   'title': 'Business Analyst',
   'address': {'address': '1039 Washington Street',
    'city': 'Philadelphia',
    'state': 'New Jersey',
    'stateCode': 'NJ',
    'postalCode': '57518',
    'coordinates': {'lat': 85.455933, 'lng': 164.246103},
    'country': 'United States'}},
  'ein': '754-660',
  'ssn': '749-524-124',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 13,
  'firstName': 'Noah',
  'lastName': 'Hernandez',
  'maidenName': '',
  'age': 41,
  'gender': 'male',
  'email': 'noah.hernandez@x.dummyjson.com',
  'phone': '+49 393-605-6968',
  'username': 'noahh',
  'password': 'noahhpass',
  'birthDate': '1984-6-5',
  'image': 'https://dummyjson.com/icon/noahh/128',
  'bloodGroup': 'AB+',

In [10]:
len(user_data["users"])

30

In [11]:
user_data["users"]

[{'id': 1,
  'firstName': 'Emily',
  'lastName': 'Johnson',
  'maidenName': 'Smith',
  'age': 29,
  'gender': 'female',
  'email': 'emily.johnson@x.dummyjson.com',
  'phone': '+81 965-431-3024',
  'username': 'emilys',
  'password': 'emilyspass',
  'birthDate': '1996-5-30',
  'image': 'https://dummyjson.com/icon/emilys/128',
  'bloodGroup': 'O-',
  'height': 193.24,
  'weight': 63.16,
  'eyeColor': 'Green',
  'hair': {'color': 'Brown', 'type': 'Curly'},
  'ip': '42.48.100.32',
  'address': {'address': '626 Main Street',
   'city': 'Phoenix',
   'state': 'Mississippi',
   'stateCode': 'MS',
   'postalCode': '29112',
   'coordinates': {'lat': -77.16213, 'lng': -92.084824},
   'country': 'United States'},
  'macAddress': '47:fa:41:18:ec:eb',
  'university': 'University of Wisconsin--Madison',
  'bank': {'cardExpire': '05/28',
   'cardNumber': '3693233511855044',
   'cardType': 'Diners Club International',
   'currency': 'GBP',
   'iban': 'GB74MH2UZLR9TRPHYNU8F8'},
  'company': {'department': 'Engineering',
   'name': 'Dooley, Kozey and Cronin',
   'title': 'Sales Manager',
   'address': {'address': '263 Tenth Street',
    'city': 'San Francisco',
    'state': 'Wisconsin',
    'stateCode': 'WI',
    'postalCode': '37657',
    'coordinates': {'lat': 71.814525, 'lng': -161.150263},
    'country': 'United States'}},
  'ein': '977-175',
  'ssn': '900-590-289',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 2,
  'firstName': 'Michael',
  'lastName': 'Williams',
  'maidenName': '',
  'age': 36,
  'gender': 'male',
  'email': 'michael.williams@x.dummyjson.com',
  'phone': '+49 258-627-6644',
  'username': 'michaelw',
  'password': 'michaelwpass',
  'birthDate': '1989-8-10',
  'image': 'https://dummyjson.com/icon/michaelw/128',
  'bloodGroup': 'B+',
  'height': 186.22,
  'weight': 76.32,
  'eyeColor': 'Red',
  'hair': {'color': 'Green', 'type': 'Straight'},
  'ip': '12.13.116.142',
  'address': {'address': '385 Fifth Street',
   'city': 'Houston',
   'state': 'Alabama',
   'stateCode': 'AL',
   'postalCode': '38807',
   'coordinates': {'lat': 22.815468, 'lng': 115.608581},
   'country': 'United States'},
  'macAddress': '79:15:78:99:60:aa',
  'university': 'Ohio State University',
  'bank': {'cardExpire': '01/30',
   'cardNumber': '3530633803003665',
   'cardType': 'JCB',
   'currency': 'USD',
   'iban': 'DE26362283149158045865'},
  'company': {'department': 'Support',
   'name': 'Spinka - Dickinson',
   'title': 'Support Specialist',
   'address': {'address': '395 Main Street',
    'city': 'Los Angeles',
    'state': 'New Hampshire',
    'stateCode': 'NH',
    'postalCode': '73442',
    'coordinates': {'lat': 79.098326, 'lng': -119.624845},
    'country': 'United States'}},
  'ein': '912-602',
  'ssn': '108-953-962',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 3,
  'firstName': 'Sophia',
  'lastName': 'Brown',
  'maidenName': '',
  'age': 43,
  'gender': 'female',
  'email': 'sophia.brown@x.dummyjson.com',
  'phone': '+81 210-652-2785',
  'username': 'sophiab',
  'password': 'sophiabpass',
  'birthDate': '1982-11-6',
  'image': 'https://dummyjson.com/icon/sophiab/128',
  'bloodGroup': 'O-',
  'height': 177.72,
  'weight': 52.6,
  'eyeColor': 'Hazel',
  'hair': {'color': 'White', 'type': 'Wavy'},
  'ip': '214.225.51.195',
  'address': {'address': '1642 Ninth Street',
   'city': 'Washington',
   'state': 'Alabama',
   'stateCode': 'AL',
   'postalCode': '32822',
   'coordinates': {'lat': 45.289366, 'lng': 46.832664},
   'country': 'United States'},
  'macAddress': '12:a3:d3:6f:5c:5b',
  'university': 'Pepperdine University',
  'bank': {'cardExpire': '10/27',
   'cardNumber': '6011212053392887',
   'cardType': 'Discover',
   'currency': 'EUR',
   'iban': 'DE12191213468288004835'},
  'company': {'department': 'Research and Development',
   'name': 'Schiller - Zieme',
   'title': 'Accountant',
   'address': {'address': '1896 Washington Street',
    'city': 'Dallas',
    'state': 'Nevada',
    'stateCode': 'NV',
    'postalCode': '88511',
    'coordinates': {'lat': 20.086743, 'lng': -34.577107},
    'country': 'United States'}},
  'ein': '963-113',
  'ssn': '638-461-822',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 4,
  'firstName': 'James',
  'lastName': 'Davis',
  'maidenName': '',
  'age': 46,
  'gender': 'male',
  'email': 'james.davis@x.dummyjson.com',
  'phone': '+49 614-958-9364',
  'username': 'jamesd',
  'password': 'jamesdpass',
  'birthDate': '1979-5-4',
  'image': 'https://dummyjson.com/icon/jamesd/128',
  'bloodGroup': 'AB+',
  'height': 193.31,
  'weight': 62.1,
  'eyeColor': 'Amber',
  'hair': {'color': 'Blonde', 'type': 'Straight'},
  'ip': '101.118.131.66',
  'address': {'address': '238 Jefferson Street',
   'city': 'Seattle',
   'state': 'Pennsylvania',
   'stateCode': 'PA',
   'postalCode': '68354',
   'coordinates': {'lat': 16.782513, 'lng': -139.34723},
   'country': 'United States'},
  'macAddress': '10:7d:df:1f:97:58',
  'university': 'University of Southern California',
  'bank': {'cardExpire': '07/30',
   'cardNumber': '5303440212268149',
   'cardType': 'Mastercard',
   'currency': 'CAD',
   'iban': 'DE01300746880579852937'},
  'company': {'department': 'Support',
   'name': 'Pagac and Sons',
   'title': 'Research Analyst',
   'address': {'address': '1622 Lincoln Street',
    'city': 'Fort Worth',
    'state': 'Pennsylvania',
    'stateCode': 'PA',
    'postalCode': '27768',
    'coordinates': {'lat': 54.91193, 'lng': -79.498328},
    'country': 'United States'}},
  'ein': '904-810',
  'ssn': '116-951-314',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 5,
  'firstName': 'Emma',
  'lastName': 'Miller',
  'maidenName': 'Johnson',
  'age': 31,
  'gender': 'female',
  'email': 'emma.miller@x.dummyjson.com',
  'phone': '+91 759-776-1614',
  'username': 'emmaj',
  'password': 'emmajpass',
  'birthDate': '1994-6-13',
  'image': 'https://dummyjson.com/icon/emmaj/128',
  'bloodGroup': 'AB-',
  'height': 192.8,
  'weight': 63.62,
  'eyeColor': 'Green',
  'hair': {'color': 'White', 'type': 'Straight'},
  'ip': '224.126.22.183',
  'address': {'address': '607 Fourth Street',
   'city': 'Jacksonville',
   'state': 'Colorado',
   'stateCode': 'CO',
   'postalCode': '26593',
   'coordinates': {'lat': 0.505589, 'lng': -157.43281},
   'country': 'United States'},
  'macAddress': '32:b9:7e:8d:f5:e8',
  'university': 'Northeastern University',
  'bank': {'cardExpire': '07/30',
   'cardNumber': '5237188057591130',
   'cardType': 'Mastercard',
   'currency': 'NZD',
   'iban': 'DE19182355652037133559'},
  'company': {'department': 'Human Resources',
   'name': 'Graham - Gulgowski',
   'title': 'Quality Assurance Engineer',
   'address': {'address': '1460 Sixth Street',
    'city': 'San Antonio',
    'state': 'Idaho',
    'stateCode': 'ID',
    'postalCode': '21965',
    'coordinates': {'lat': 44.346545, 'lng': -26.944701},
    'country': 'United States'}},
  'ein': '403-505',
  'ssn': '526-210-885',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'admin'},
 {'id': 6,
  'firstName': 'Olivia',
  'lastName': 'Wilson',
  'maidenName': '',
  'age': 23,
  'gender': 'female',
  'email': 'olivia.wilson@x.dummyjson.com',
  'phone': '+91 607-295-6448',
  'username': 'oliviaw',
  'password': 'oliviawpass',
  'birthDate': '2002-4-20',
  'image': 'https://dummyjson.com/icon/oliviaw/128',
  'bloodGroup': 'B+',
  'height': 182.61,
  'weight': 58,
  'eyeColor': 'Hazel',
  'hair': {'color': 'Gray', 'type': 'Curly'},
  'ip': '249.178.112.207',
  'address': {'address': '547 First Street',
   'city': 'Fort Worth',
   'state': 'Tennessee',
   'stateCode': 'TN',
   'postalCode': '83843',
   'coordinates': {'lat': 75.32627, 'lng': -26.15285},
   'country': 'United States'},
  'macAddress': '9c:7f:ea:34:18:19',
  'university': 'University of North Carolina--Chapel Hill',
  'bank': {'cardExpire': '06/30',
   'cardNumber': '376320072452632',
   'cardType': 'American Express',
   'currency': 'NZD',
   'iban': 'DE21153814367894194071'},
  'company': {'department': 'Product Management',
   'name': 'Pfannerstill Inc',
   'title': 'Research Analyst',
   'address': {'address': '425 Sixth Street',
    'city': 'Indianapolis',
    'state': 'Oklahoma',
    'stateCode': 'OK',
    'postalCode': '74263',
    'coordinates': {'lat': 74.986644, 'lng': -132.916888},
    'country': 'United States'}},
  'ein': '921-709',
  'ssn': '836-772-168',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 7,
  'firstName': 'Alexander',
  'lastName': 'Jones',
  'maidenName': '',
  'age': 39,
  'gender': 'male',
  'email': 'alexander.jones@x.dummyjson.com',
  'phone': '+61 260-824-4986',
  'username': 'alexanderj',
  'password': 'alexanderjpass',
  'birthDate': '1986-10-20',
  'image': 'https://dummyjson.com/icon/alexanderj/128',
  'bloodGroup': 'AB-',
  'height': 153.89,
  'weight': 77.42,
  'eyeColor': 'Blue',
  'hair': {'color': 'White', 'type': 'Straight'},
  'ip': '166.204.84.32',
  'address': {'address': '664 Maple Street',
   'city': 'Indianapolis',
   'state': 'Delaware',
   'stateCode': 'DE',
   'postalCode': '86684',
   'coordinates': {'lat': 35.289664, 'lng': 7.063255},
   'country': 'United States'},
  'macAddress': 'd2:64:58:2d:1c:46',
  'university': 'University of Illinois--Urbana-Champaign',
  'bank': {'cardExpire': '12/29',
   'cardNumber': '5189302549548693',
   'cardType': 'Mastercard',
   'currency': 'PKR',
   'iban': 'DE67517655968963441488'},
  'company': {'department': 'Engineering',
   'name': 'Dickens - Beahan',
   'title': 'Web Developer',
   'address': {'address': '996 Eighth Street',
    'city': 'Washington',
    'state': 'Kansas',
    'stateCode': 'KS',
    'postalCode': '27858',
    'coordinates': {'lat': -75.462366, 'lng': -128.025697},
    'country': 'United States'}},
  'ein': '638-127',
  'ssn': '722-993-925',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 8,
  'firstName': 'Ava',
  'lastName': 'Taylor',
  'maidenName': '',
  'age': 28,
  'gender': 'female',
  'email': 'ava.taylor@x.dummyjson.com',
  'phone': '+1 458-853-7877',
  'username': 'avat',
  'password': 'avatpass',
  'birthDate': '1997-8-25',
  'image': 'https://dummyjson.com/icon/avat/128',
  'bloodGroup': 'AB-',
  'height': 168.47,
  'weight': 57.08,
  'eyeColor': 'Hazel',
  'hair': {'color': 'Red', 'type': 'Kinky'},
  'ip': '150.73.197.233',
  'address': {'address': '1197 First Street',
   'city': 'Fort Worth',
   'state': 'Rhode Island',
   'stateCode': 'RI',
   'postalCode': '24771',
   'coordinates': {'lat': -81.194833, 'lng': -87.948158},
   'country': 'United States'},
  'macAddress': '8d:2e:c2:d6:e7:a8',
  'university': 'University of Wisconsin--Madison',
  'bank': {'cardExpire': '08/30',
   'cardNumber': '5349974103330333',
   'cardType': 'Mastercard',
   'currency': 'EUR',
   'iban': 'FR94ZM2MMGL1EVYQE1ZLCVCFH83'},
  'company': {'department': 'Marketing',
   'name': 'Nikolaus Inc',
   'title': 'Chief Executive Officer',
   'address': {'address': '930 Lincoln Street',
    'city': 'Austin',
    'state': 'Colorado',
    'stateCode': 'CO',
    'postalCode': '47592',
    'coordinates': {'lat': 87.970083, 'lng': -42.769351},
    'country': 'United States'}},
  'ein': '297-762',
  'ssn': '257-419-109',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 9,
  'firstName': 'Ethan',
  'lastName': 'Martinez',
  'maidenName': '',
  'age': 34,
  'gender': 'male',
  'email': 'ethan.martinez@x.dummyjson.com',
  'phone': '+92 933-608-5081',
  'username': 'ethanm',
  'password': 'ethanmpass',
  'birthDate': '1991-2-12',
  'image': 'https://dummyjson.com/icon/ethanm/128',
  'bloodGroup': 'AB+',
  'height': 159.19,
  'weight': 68.81,
  'eyeColor': 'Hazel',
  'hair': {'color': 'Purple', 'type': 'Curly'},
  'ip': '63.191.127.71',
  'address': {'address': '466 Pine Street',
   'city': 'San Antonio',
   'state': 'Louisiana',
   'stateCode': 'LA',
   'postalCode': '72360',
   'coordinates': {'lat': 74.074918, 'lng': -25.312703},
   'country': 'United States'},
  'macAddress': '59:e:9e:e3:29:da',
  'university': 'Syracuse University',
  'bank': {'cardExpire': '10/27',
   'cardNumber': '3598603288061479',
   'cardType': 'JCB',
   'currency': 'GBP',
   'iban': 'GB26PND7D83JTW4HL6LZ71'},
  'company': {'department': 'Support',
   'name': 'Gorczany - Gottlieb',
   'title': 'Legal Counsel',
   'address': {'address': '1597 Oak Street',
    'city': 'Chicago',
    'state': 'Florida',
    'stateCode': 'FL',
    'postalCode': '28100',
    'coordinates': {'lat': -67.45208, 'lng': -23.209886},
    'country': 'United States'}},
  'ein': '790-434',
  'ssn': '569-650-348',
  'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 10,
  'firstName': 'Isabella',
  'lastName': 'Anderson',
  'maidenName': 'Davis',
  'age': 32,
  'gender': 'female',
  'email': 'isabella.anderson@x.dummyjson.com',
  'phone': '+49 770-658-4885',
  'username': 'isabellad',
  'password': 'isabelladpass',
  'birthDate': '1993-6-10',
  'image': 'https://dummyjson.com/icon/isabellad/128',
  'bloodGroup': 'A-',
  'height': 150.56,
  'weight': 50.1,
  'eyeColor': 'Brown',
  'hair': {'color': 'Blonde', 'type': 'Curly'},
  'ip': '114.9.114.205',
  'address': {'address': '1964 Oak Street',
   'city': 'New York',
   'state': 'Utah',
   'stateCode': 'UT',
   'postalCode': '89352',
   'coordinates': {'lat': 41.331324, 'lng': 151.782727},
   'country': 'United States'},
  'macAddress': 'b1:b0:d0:a2:82:80',
  'university': 'California Institute of Technology (Caltech)',
  'bank': {'cardExpire': '03/30',
   'cardNumber': '3602093733952858',
   'cardType': 'Diners Club International',
   'currency': 'USD',
   'iban': 'DE12934874962442340025'},
  'company': {'department': 'Marketing',
   'name': 'Pollich - Hilpert',
   'title': 'Chief Financial Officer',
   'address': {'address': '1029 Adams Street',
    'city': 'San Diego',
    'state': 'Maryland',
    'stateCode': 'MD',
    'postalCode': '63847',
    'coordinates': {'lat': -25.843393, 'lng': -62.692681},
    'country': 'United States'}},
  'ein': '127-297',
  'ssn': '902-438-728',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 11,
  'firstName': 'Liam',
  'lastName': 'Garcia',
  'maidenName': '',
  'age': 30,
  'gender': 'male',
  'email': 'liam.garcia@x.dummyjson.com',
  'phone': '+92 870-217-6201',
  'username': 'liamg',
  'password': 'liamgpass',
  'birthDate': '1995-6-6',
  'image': 'https://dummyjson.com/icon/liamg/128',
  'bloodGroup': 'AB-',
  'height': 162.32,
  'weight': 93.16,
  'eyeColor': 'Violet',
  'hair': {'color': 'Red', 'type': 'Wavy'},
  'ip': '56.201.85.9',
  'address': {'address': '576 Fifth Street',
   'city': 'Denver',
   'state': 'South Dakota',
   'stateCode': 'SD',
   'postalCode': '57252',
   'coordinates': {'lat': -66.218177, 'lng': -145.340165},
   'country': 'United States'},
  'macAddress': '31:9a:28:8b:99:6c',
  'university': 'Ohio State University',
  'bank': {'cardExpire': '12/29',
   'cardNumber': '3614993744940956',
   'cardType': 'Diners Club International',
   'currency': 'USD',
   'iban': 'DE65581882748067758114'},
  'company': {'department': 'Services',
   'name': 'Considine - Torp',
   'title': 'Web Developer',
   'address': {'address': '27 Cedar Street',
    'city': 'Philadelphia',
    'state': 'Connecticut',
    'stateCode': 'CT',
    'postalCode': '79574',
    'coordinates': {'lat': -81.841588, 'lng': 31.79423},
    'country': 'United States'}},
  'ein': '326-604',
  'ssn': '933-784-949',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 12,
  'firstName': 'Mia',
  'lastName': 'Rodriguez',
  'maidenName': '',
  'age': 25,
  'gender': 'female',
  'email': 'mia.rodriguez@x.dummyjson.com',
  'phone': '+49 989-461-8403',
  'username': 'miar',
  'password': 'miarpass',
  'birthDate': '2000-8-4',
  'image': 'https://dummyjson.com/icon/miar/128',
  'bloodGroup': 'O-',
  'height': 188.08,
  'weight': 56.03,
  'eyeColor': 'Blue',
  'hair': {'color': 'Purple', 'type': 'Wavy'},
  'ip': '11.72.253.90',
  'address': {'address': '1627 Sixth Street',
   'city': 'Jacksonville',
   'state': 'West Virginia',
   'stateCode': 'WV',
   'postalCode': '41810',
   'coordinates': {'lat': 24.857497, 'lng': -34.865429},
   'country': 'United States'},
  'macAddress': '53:d7:a4:6:1e:58',
  'university': 'William & Mary',
  'bank': {'cardExpire': '02/29',
   'cardNumber': '343932350909214',
   'cardType': 'American Express',
   'currency': 'CAD',
   'iban': 'DE77118774979880310165'},
  'company': {'department': 'Accounting',
   'name': 'Miller, Schowalter and Wisozk',
   'title': 'Business Analyst',
   'address': {'address': '1039 Washington Street',
    'city': 'Philadelphia',
    'state': 'New Jersey',
    'stateCode': 'NJ',
    'postalCode': '57518',
    'coordinates': {'lat': 85.455933, 'lng': 164.246103},
    'country': 'United States'}},
  'ein': '754-660',
  'ssn': '749-524-124',
  'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
  'crypto': {'coin': 'Bitcoin',
   'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a',
   'network': 'Ethereum (ERC20)'},
  'role': 'moderator'},
 {'id': 13,
  'firstName': 'Noah',
  'lastName': 'Hernandez',
  'maidenName': '',
  'age': 41,
  'gender': 'male',
  'email': 'noah.hernandez@x.dummyjson.com',
  'phone': '+49 393-605-6968',
  'username': 'noahh',
  'password': 'noahhpass',
  'birthDate': '1984-6-5',
  'image': 'https://dummyjson.com/icon/noahh/128',
  'bloodGroup': 'AB+',

In [15]:
item_data = pd.DataFrame(user_data["users"])
item_data

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,address,macAddress,university,bank,company,ein,ssn,userAgent,crypto,role
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,"{'address': '626 Main Street', 'city': 'Phoeni...",47:fa:41:18:ec:eb,University of Wisconsin--Madison,"{'cardExpire': '05/28', 'cardNumber': '3693233...","{'department': 'Engineering', 'name': 'Dooley,...",977-175,900-590-289,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,"{'address': '385 Fifth Street', 'city': 'Houst...",79:15:78:99:60:aa,Ohio State University,"{'cardExpire': '01/30', 'cardNumber': '3530633...","{'department': 'Support', 'name': 'Spinka - Di...",912-602,108-953-962,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,"{'address': '1642 Ninth Street', 'city': 'Wash...",12:a3:d3:6f:5c:5b,Pepperdine University,"{'cardExpire': '10/27', 'cardNumber': '6011212...","{'department': 'Research and Development', 'na...",963-113,638-461-822,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,"{'address': '238 Jefferson Street', 'city': 'S...",10:7d:df:1f:97:58,University of Southern California,"{'cardExpire': '07/30', 'cardNumber': '5303440...","{'department': 'Support', 'name': 'Pagac and S...",904-810,116-951-314,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,"{'address': '607 Fourth Street', 'city': 'Jack...",32:b9:7e:8d:f5:e8,Northeastern University,"{'cardExpire': '07/30', 'cardNumber': '5237188...","{'department': 'Human Resources', 'name': 'Gra...",403-505,526-210-885,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
5,6,Olivia,Wilson,,23,female,olivia.wilson@x.dummyjson.com,+91 607-295-6448,oliviaw,oliviawpass,...,"{'address': '547 First Street', 'city': 'Fort ...",9c:7f:ea:34:18:19,University of North Carolina--Chapel Hill,"{'cardExpire': '06/30', 'cardNumber': '3763200...","{'department': 'Product Management', 'name': '...",921-709,836-772-168,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
6,7,Alexander,Jones,,39,male,alexander.jones@x.dummyjson.com,+61 260-824-4986,alexanderj,alexanderjpass,...,"{'address': '664 Maple Street', 'city': 'India...",d2:64:58:2d:1c:46,University of Illinois--Urbana-Champaign,"{'cardExpire': '12/29', 'cardNumber': '5189302...","{'department': 'Engineering', 'name': 'Dickens...",638-127,722-993-925,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
7,8,Ava,Taylor,,28,female,ava.taylor@x.dummyjson.com,+1 458-853-7877,avat,avatpass,...,"{'address': '1197 First Street', 'city': 'Fort...",8d:2e:c2:d6:e7:a8,University of Wisconsin--Madison,"{'cardExpire': '08/30', 'cardNumber': '5349974...","{'department': 'Marketing', 'name': 'Nikolaus ...",297-762,257-419-109,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
8,9,Ethan,Martinez,,34,male,ethan.martinez@x.dummyjson.com,+92 933-608-5081,ethanm,ethanmpass,...,"{'address': '466 Pine Street', 'city': 'San An...",59:e:9e:e3:29:da,Syracuse University,"{'cardExpire': '10/27', 'cardNumber': '3598603...","{'department': 'Support', 'name': 'Gorczany - ...",790-434,569-650-348,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
9,10,Isabella,Anderson,Davis,32,female,isabella.anderson@x.dummyjson.com,+49 770-658-4885,isabellad,isabelladpass,...,"{'address': '1964 Oak Street', 'city': 'New Yo...",b1:b0:d0:a2:82:80,California Institute of Technology (Caltech),"{'cardExpire': '03/30', 'cardNumber': '3602093...","{'department': 'Marketing', 'name': 'Pollich -...",127-297,902-438-728,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
10,11,Liam,Garcia,,30,male,liam.garcia@x.dummyjson.com,+92 870-217-6201,liamg,liamgpass,...,"{'address': '576 Fifth Street', 'city': 'Denve...",31:9a:28:8b:99:6c,Ohio State University,"{'cardExpire': '12/29', 'cardNumber': '3614993...","{'department': 'Services', 'name': 'Considine ...",326-604,933-784-949,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
11,12,Mia,Rodriguez,,25,female,mia.rodriguez@x.dummyjson.com,+49 989-461-8403,miar,miarpass,...,"{'address': '1627 Sixth Street', 'city': 'Jack...",53:d7:a4:6:1e:58,William & Mary,"{'cardExpire': '02/29', 'cardNumber': '3439323...","{'department': 'Accounting', 'name': 'Miller, ...",754-660,749-524-124,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
12,13,Noah,Hernandez,,41,male,noah.hernandez@x.dummyjson.com,+49 393-605-6968,noahh,noahhpass,...,"{'address': '1413 Maple Street', 'city': 'New ...",d4:fe:ae:8f:eb:a3,New York University (NYU),"{'cardExpire': '03/30', 'cardNumber': '6262462...","{'department': 'Engineering', 'name': 'Botsfor...",877-628,660-847-389,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
13,14,Charlotte,Lopez,Martinez,37,female,charlotte.lopez@x.dummyjson.com,+44 373-953-5028,charlottem,charlottempass,...,"{'address': '208 Second Street', 'city': 'Colu...",f6:ff:37:aa:6c:f1,Northeastern University,"{'cardExpire': '12/27', 'cardNumber': '3634388...","{'department': 'Accounting', 'name': 'Zulauf a...",364-782,255-491-479,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
14,15,William,Gonzalez,,33,male,william.gonzalez@x.dummyjson.com,+81 905-252-7319,williamg,williamgpass,...,"{'address': '31 Maple Street', 'city': 'San Jo...",f5:68:28:f9:ec:89,Tufts University,"{'cardExpire': '05/30', 'cardNumber': '6228256...","{'department': 'Marketing', 'name': 'Spinka - ...",830-515,690-544-755,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",moderator
15,16,Avery,Perez,,26,female,avery.perez@x.dummyjson.com,+61 731-431-3457,averyp,averyppass,...,"{'address': '1125 First Street', 'city': 'Colu...",b3:ff:f3:c5:37:46,Harvard University,"{'cardExpire': '08/29', 'cardNumber': '3780240...","{'department': 'Accounting', 'name': 'Herzog I...",348-493,679-523-686,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
16,17,Evelyn,Sanchez,,38,female,evelyn.sanchez@x.dummyjson.com,+1 623-880-6871,evelyns,evelynspass,...,"{'address': '1170 Lincoln Street', 'city': 'Sa...",f8:e5:bd:43:bc:d8,Washington University in St. Louis,"{'cardExpire': '01/29', 'cardNumber': '3514443...","{'department': 'Support', 'name': 'Predovic - ...",604-817,689-332-644,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
17,18,Logan,Torres,,32,male,logan.torres@x.dummyjson.com,+81 507-434-8733,logant,logantpass,...,"{'address': '907 Seventh Street', 'city': 'Col...",40:d:5c:1:7d:bf,University of Illinois--Urbana-Champaign,"{'cardExpire': '04/30', 'cardNumber': '6258651...","{'department': 'Training', 'name': 'Jast - Nad...",576-218,806-639-934,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
18,19,Abigail,Rivera,,29,female,abigail.rivera@x.dummyjson.com,+91 228-363-7806,abigailr,abigailrpass,...,"{'address': '996 Oak Street', 'city': 'Chicago...",1d:a6:58:2a:e5:e4,California Institute of Technology (Caltech),"{'cardExpire': '01/27', 'cardNumber': '6011399...","{'department': 'Human Resources', 'name': 'Pro...",173-637,655-823-929,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
19,20,Jackson,Evans,,35,male,jackson.evans@x.dummyjson.com,+44 468-628-6686,jacksone,jacksonepass,...,"{'address': '1873 Main Street', 'city': 'New Y...",81:14:1:97:88:85,Ohio State University,"{'cardExpire': '07/30', 'cardNumber': '3767606...","{'department': 'Legal', 'name': 'Kuhlman LLC',...",843-260,248-787-886,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
20,21,Madison,Collins,,27,female,madison.collins@x.dummyjson.com,+81 259-957-5711,madisonc,madisoncpass,...,"{'address': '1892 Lincoln Street', 'city': 'Ph...",13:b0:d0:23:4d:26,University of Pennsylvania,"{'cardExpire': '09/27', 'cardNumber': '5551259...","{'department': 'Engineering', 'name': 'Mayer -...",716-166,457-258-950,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
21,22,Elijah,Stewart,,34,male,elijah.stewart@x.dummyjson.com,+44 468-357-7872,elijahs,elijahspass,...,"{'address': '1701 Eighth Street', 'city': 'Col...",75:17:c6:35:fc:6d,Georgetown University,"{'cardExpire': '05/28', 'cardNumber': '3648138...","{'department': 'Legal', 'name': 'Langworth Gro...",520-394,287-380-801,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
22,23,Chloe,Morales,,40,female,chloe.morales@x.dummyjson.com,+92 468-541-7133,chloem,chloempass,...,"{'address': '401 Fourth Street', 'city': 'Dall...",fc:f:29:e1:37:b8,Syracuse University,"{'cardExpire': '09/30', 'cardNumber': '3470362...","{'department': 'Sales', 'name': 'Grady LLC', '...",913-597,938-883-163,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
23,24,Mateo,Nguyen,,31,male,mateo.nguyen@x.dummyjson.com,+1 341-597-6694,mateon,mateonpass,...,"{'address': '1578 Fourth Street', 'city': 'Col...",a7:26:10:7a:36:29,Columbia University,"{'cardExpire': '12/29', 'cardNumber': '4021840...","{'department': 'Accounting', 'name': 'Spinka L...",229-249,416-877-230,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
24,25,Harper,Kelly,Evans,28,female,harper.kelly@x.dummyjson.com,+92 518-863-2863,harpere,harperepass,...,"{'address': '1591 Adams Street', 'city': 'Phil...",b:ff:33:67:94:e4,Boston College,"{'cardExpire': '06/27', 'cardNumber': '4488823...","{'department': 'Legal', 'name': 'Leffler, Rolf...",592-557,209-544-548,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
25,26,Evelyn,Gonzalez,,36,female,evelyn.gonzalez@x.dummyjson.com,+61 708-508-4638,evelyng,evelyngpass,...,"{'address': '1065 Lincoln Street', 'city': 'Da...",89:5e:5a:2a:72:42,Washington University in St. Louis,"{'cardExpire': '08/28', 'cardNumber': '6011735...","{'department': 'Accounting', 'name': 'Tromp, G...",569-275,487-680-127,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
26,27,Daniel,Cook,,42,male,daniel.cook@x.dummyjson.com,+44 254-761-6843,danielc,danielcpass,...,"{'address': '1163 Pine Street', 'city': 'Los A...",6e:73:dc:3a:85:10,Columbia University,"{'cardExpire': '05/29', 'cardNumber': '5485409...","{'department': 'Support', 'name': 'Morissette,...",585-905,645-515-583,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
27,28,Lily,Lee,Brown,30,female,lily.lee@x.dummyjson.com,+1 808-757-9867,lilyb,lilybpass,...,"{'address': '1946 Oak Street', 'city': 'Phoeni...",18:b6:c7:a:50:3f,Johns Hopkins University,"{'cardExpire': '12/28', 'cardNumber': '5551782...","{'department': 'Product Management', 'name': '...",229-776,358-185-671,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
28,29,Henry,Hill,,39,male,henry.hill@x.dummyjson.com,+1 240-833-4680,henryh,henryhpass,...,"{'address': '1837 Maple Street', 'city': 'Indi...",fa:c3:1b:21:5f:44,University of Illinois--Urbana-Champaign,"{'cardExpire': '11/29', 'cardNumber': '3625097...","{'department': 'Services', 'name': 'Gerlach, F...",118-957,925-686-100,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user
29,30,Addison,Wright,,33,female,addison.wright@x.dummyjson.com,+1 514-384-3300,addisonw,addisonwpass,...,"{'address': '568 Tenth Street', 'city': 'San F...",fb:0:94:21:16:c,Syracuse University,"{'cardExpire': '06/28', 'cardNumber': '5274971...","{'department': 'Services', 'name': 'Kreiger In...",415-286,804-492-390,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",user